version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-memory
    restart: always
    ports:
      - "7475:7474"  # HTTP (mapped to 7475 to avoid conflict)
      - "7688:7687"  # Bolt (mapped to 7688 to avoid conflict)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      # Set initial password (change this!)
      - NEO4J_AUTH=neo4j/password123
      # Memory configuration
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=512m
      # Enable APOC procedures
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      # Enable query logging
      - NEO4J_db_logs_query_enabled=VERBOSE
      - NEO4J_db_logs_query_threshold=0

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local